ALTER TABLE xformgen4.wkf_flujo DROP FOREIGN KEY FKFLUJO_SISTEMA;
ALTER TABLE xformgen4.wkf_etapa  DROP FOREIGN KEY FKETAPA_FLUJO;
ALTER TABLE xformgen4.wkf_accionDestino  DROP FOREIGN KEY FK_ACCIONDESTINO_FLUJO;

ALTER TABLE xformgen4.wkf_flujo 
ADD COLUMN mxGraph TEXT NULL AFTER fSistema,
CHANGE COLUMN PFLUJO pFlujo INT(11) NOT NULL ,
CHANGE COLUMN CNOMBRE cNombre VARCHAR(50) NOT NULL ,
CHANGE COLUMN CTITULO cTitulo VARCHAR(50) NULL DEFAULT NULL ,
CHANGE COLUMN NDURACIONLIMITE nDuracionLimite INT(11) NULL DEFAULT NULL COMMENT 'Limite de duracion total en minutos para que el flujo finalice' ,
CHANGE COLUMN CURL cURL VARCHAR(50) NULL DEFAULT NULL COMMENT 'URL dentro de la aplicacion vinculada al flujo' ,
CHANGE COLUMN FSISTEMA fSistema INT(11) NULL DEFAULT NULL
;

ALTER TABLE `xformgen4`.`wkf_flujo` 
ADD UNIQUE INDEX `IUFLUJO_NOMBRE` (`cNombre` ASC)
;


ALTER TABLE xformgen4.wkf_flujo 
ADD CONSTRAINT FKFLUJO_SISTEMA
  FOREIGN KEY (fSistema)
  REFERENCES xformgen4.tSistema (pSistema);
  
ALTER TABLE xformgen4.wkf_etapa 
  ADD CONSTRAINT FKETAPA_FLUJO FOREIGN KEY (fFlujo) REFERENCES wkf_flujo (pFlujo);
ALTER TABLE xformgen4.wkf_accionDestino 
  ADD CONSTRAINT FK_ACCIONDESTINO_FLUJO FOREIGN KEY (fSubFlujo) REFERENCES wkf_flujo (pFlujo);
