ALTER TABLE `xformgen4`.`wkf_accionFuncion` 
	DROP FOREIGN KEY `FK_WKFACCIONFUNCION_ACCION`
;
    
ALTER TABLE `xformgen4`.`wkf_accionFuncion` 
CHANGE COLUMN `PACCION` `pAccion` INT(11) NOT NULL ,
CHANGE COLUMN `PSECUENCIA` `pSecuencia` INT(5) NOT NULL ,
CHANGE COLUMN `CFUNCION` `cFuncion` VARCHAR(100) NOT NULL ,
CHANGE COLUMN `CALIAS` `cAlias` VARCHAR(30) NULL DEFAULT NULL ,
CHANGE COLUMN `CTPEJECUCION` `cTpEjecucion` VARCHAR(10) NOT NULL DEFAULT 'SQL' 
;

ALTER TABLE `xformgen4`.`wkf_accionFuncion` 
ADD CONSTRAINT `FK_WKFACCIONFUNCION_ACCION`
  FOREIGN KEY (`pAccion`)
  REFERENCES `xformgen4`.`wkf_accion` (`pAccion`);
  